[toolchain]
profile = "minimal"
# channel = "nightly-2023-03-29"
# channel = "nightly-2023-12-01"
channel = "nightly"
components = ["rust-src", "rustfmt", "clippy"]
targets = [
    "riscv64gc-unknown-none-elf",
]
